In [1]:
import pandas as pd

In [10]:
glacier_data = pd.read_csv("glacier_species_checklist.csv", encoding="latin-1")
glacier_data.head()

,Park Code,Park Name,Category,Category Sort,Order,Family,Taxon Code,TSN,Taxon Record Status,Scientific Name,Common Names,Synonyms,Occurrence
0,GLAC,Glacier National Park,Mammal,1,Artiodactyla,Bovidae,95063,180713,Active,Oreamnos americanus,mountain goat,NaN,Present
1,GLAC,Glacier National Park,Mammal,1,Artiodactyla,Bovidae,95061,180711,Active,Ovis canadensis,bighorn sheep,NaN,Present
2,GLAC,Glacier National Park,Mammal,1,Artiodactyla,Cervidae,95052,180703,Active,Alces alces,moose,NaN,Present
3,GLAC,Glacier National Park,Mammal,1,Artiodactyla,Cervidae,95042,180695,Active,Cervus elaphus,elk,NaN,Present
4,GLAC,Glacier National Park,Mammal,1,Artiodactyla,Cervidae,95045,180698,Active,Odocoileus hemionus,mule deer,NaN,Present

In [11]:
glacier_data = glacier_data[["Park Name", "Category", "Scientific Name", "Common Names", "Occurrence"]]

In [12]:
glacier_data.head()

,Park Name,Category,Scientific Name,Common Names,Occurrence
0,Glacier National Park,Mammal,Oreamnos americanus,mountain goat,Present
1,Glacier National Park,Mammal,Ovis canadensis,bighorn sheep,Present
2,Glacier National Park,Mammal,Alces alces,moose,Present
3,Glacier National Park,Mammal,Cervus elaphus,elk,Present
4,Glacier National Park,Mammal,Odocoileus hemionus,mule deer,Present

In [16]:
glacier_data.rename(columns={"Category":"Taxon Group","Common Names":"Common Name"}, inplace=True)

In [18]:
glacier_data.head()

,Park Name,Taxon Group,Scientific Name,Common Name,Occurrence
0,Glacier National Park,Mammal,Oreamnos americanus,mountain goat,Present
1,Glacier National Park,Mammal,Ovis canadensis,bighorn sheep,Present
2,Glacier National Park,Mammal,Alces alces,moose,Present
3,Glacier National Park,Mammal,Cervus elaphus,elk,Present
4,Glacier National Park,Mammal,Odocoileus hemionus,mule deer,Present

In [19]:
glacier_data.to_csv("cleaned_glacier_data_MOSHER.csv")